#ifndef ACHIEVEMENT_LIST_H
#define ACHIEVEMENT_LIST_H
#include "achievement.h"
static Achievement achievementList[] = {
    Achievement(_("Elite Slayer"), _("Defeat an Elite-Type monster."), _("KillEliteMonster"), _("Items.Medkit")),
    Achievement(_("Advancement"),_("Complete a Teleporter event."),_("CompleteTeleporter"),_("Items.BossDamageBonus")),
    Achievement(_("The Basics"),_("Discover 10 Unique white items."),_("Discover10UniqueTier1"),_("Items.Crowbar")),
    Achievement(_("Warrior"),_("Reach and complete the 3rd Teleporter event without dying."),_("CompleteThreeStages"),_("Characters.Bandit2")),
    Achievement(_("The Lone Surviror"),_("Stay alive for 30 consecutive minutes"),_("StayAlive1"),_("Items.ExtraLife")),
    Achievement(_("Learning Process"),_("Die 5 times."),_("Die5Times"),_("Items.Bear")),
    Achievement(_("Funded!"),_("Collect $30,480 total gold."),_("TotalMoneyCollected"),_("Items.GoldGat")),
    Achievement(_("Experimenting"),_("Pick up 5 different types of Equipment."),_("Discover5Equipment"),_("Items.EquipmentMagazine")),
    Achievement(_("Verified"),_("Complete the first Teleporter event 5 times."),_("RepeatFirstTeleporter"),_("Characters.Toolbot")),
    Achievement(_("Keyed Up"),_("Defeat the Teleporter boss under 15 seconds."),_("KillBossQuick"),_("Items.TreasureCache")),
    Achievement(_("\"Is This Bugged\""),_("Fail the Shrine of Chance 3 times in a row."),_("FailShrineChance"),_("Items.Hoof")),
    Achievement(_("Macho"),_("Deal 5000 damage in one shot."),_("HardHitter"),_("Items.ShockNearby")),
    Achievement(_("Deja Vu?"),_("Loop back to the first stage."),_("LoopOnce"),_("Items.BounceNearby")),
    Achievement(_("Bookworm"),_("Collect 10 Monster or Environment Logs."),_("LogCollector"),_("Items.Scanner")),
    Achievement(_("Blockade Breaker"),_("Kill 15 boss monsters in a single run."),_("KillBossQuantityInRun"),_("Items.LunarSkillReplacements")),
    Achievement(_("Engineering Perfection"),_("Complete 30 stages."),_("Complete30StagesCareer"),_("Characters.Engineer")),
    Achievement(_("Multikill!"),_("Kill 15 enemies simultaneously."),_("MajorMultikill"),_("Items.BurnNearby")),
    Achievement(_("Guidance Offline"),_("Defeat the unique guardian of Siren's Call."),_("DefeatSuperRoboBallBoss"),_("Characters.Loader")),
    Achievement(_("Slaughter"),_("Defeat 3000 enemies."),_("KillTotalEnemies"),_("Items.Infusion")),
    Achievement(_("Cosmic Explorer"),_("Discover and enter three unique portals."),_("UseThreePortals"),_("Items.Tonic")),
    Achievement(_("I Love Dying!"),_("Die 20 times."),_("Die20Times"),_("Items.DeathProjectile")),
    Achievement(_("Flawless"),_("Fully charge a Teleporter without getting hit."),_("CompleteTeleporterWithoutInjury"),_("Items.SecondarySkillMagazine")),
    Achievement(_("Going Fast Recommended"),_("Reach +300% movespeed (includes sprinting)."),_("MoveSpeed"),_("Items.JumpBoost")),
    Achievement(_("Mechanic"),_("Repair 30 drones or turrets."),_("TotalDronesRepaired"),_("Items.DroneBackup")),
    Achievement(_("Warm For Life"),_("Die three times while burning."),_("BurnToDeath"),_("Items.Cleanse")),
    Achievement(_("Ascendant"),_("Defeat the Teleporter bosses after activating 2 Shrines of the Mountain."),_("CompleteMultiBossShrine"),_("Items.Lightning")),
    Achievement(_("Warmonger"),_("Complete 3 Combat Shrines in a single stage."),_("MultiCombatShrine"),_("Items.WarCryOnMultiKill")),
    Achievement(_("Washed Away"),_("Beat the game."),_("CompleteMainEnding"),_("Characters.Captain")),
    Achievement(_("Pause."),_("Free the survivor suspended in time."),_("FreeMage"),_("Characters.Mage")),
    Achievement(_("True Respite"),_("Obliterate yourself at the Obelisk."),_("CompleteUnknownEnding"),_("Characters.Mercenary")),
    Achievement(_("Cut Down"),_("Defeat 500 elite monsters."),_("KillElitesMilestone"),_("Items.ExecuteLowHealthElite")),
    Achievement(_("Cleanup Duty"),_("Destroy 20 flying rocks in Sky Meadow."),_("CleanupDuty"),_("Items.Recycle")),
    Achievement(_("Rapidfire"),_("Reach +200% attack speed."),_("AttackSpeed"),_("Items.AttackSpeedOnCrit")),
    Achievement(_("...To Be Left Alone"),_("Stabilize the Cell in the Void Fields."),_("BeatArena"),_("Characters.Croco")),
    Achievement(_("Never Back Down"),_("In 4 consecutive stages don't leave the teleporter radius until it is fully charged."),_("NeverBackDown"),_("Items.FocusConvergence")),
    Achievement(_("Blackout"),_("Defeat the unique guardian of Gilded Coast without any beacons deactivating."),_("KillGoldTitanInOneCycle"),_("Items.Gateway")),
    Achievement(_("One with the Woods"),_("Fully upgrade a Shrine of the Woods."),_("MaxHealingShrine"),_("Items.PassiveHealing")),
    Achievement(_("...Maybe One More."),_("Duplicate the same item 7 times in a row with a 3D Printer."),_("RepeatedlyDuplicateItems"),_("Items.Firework")),
    Achievement(_("Her Concepts"),_("Find the Altar to N'kuhana."),_("FindDevilAltar"),_("Items.NovaOnHeal")),
    Achievement(_("Naturopath"),_("Without healing, reach and complete the 3rd Teleporter event."),_("CompleteThreeStagesWithoutHealing"),_("Items.IncreaseHealing")),
    Achievement(_("Death Do Us Part"),_("Discover the hidden chamber in the Abandoned Aqueduct."),_("KillElementalLemurians"),_("Items.ElementalRings")),
    Achievement(_("Trial of Honor"),_("Complete the Trial of Honor."),_("ObtainArtifactEliteOnly"),_("Artifacts.EliteOnly")),
    Achievement(_("Automation Activation"),_("Activate 6 turrets in a single run."),_("AutomationActivation"),_("Items.Squid")),
    Achievement(_("Huntress: Finishing Touch"),_("As Huntress, land a killing blow with every possible hit of a single glaive."),_("HuntressAllGlaiveBouncesKill"),_("Skills.Huntress.FlurryArrow")),
    Achievement(_("Commando: Godspeed"),_("As Commando, fully charge tje first-stage teleporter before the timer hits 5 minutes."),_("CommandoFastFirstStageClear"),_("Skills.Commando.SlideJet")),
    Achievement(_("Trial of Command"),_("Complete the Trial of Command."),_("ObtainArtifactCommand"),_("Artifacts.Command")),
    Achievement(_("Power Plant"),_("Repair the broken robot with an Escape Pod's Fuel Array"),_("RescueTreebot"),_("Characters.Treebot")),
    Achievement(_("Moon Worshiper"),_("Carry 5 Lunar items in a single run."),_("CarryLunarItems"),_("Items.Meteor")),
    Achievement(_("Deicide"),_("Defeat an Elite boss on Monsoon difficulty"),_("HardEliteBossKill"),_("Items.KillEliteFrenzy")),
    Achievement(_("[REDACTED]"),_("Open the Timed Security Chest on Rallypoint Delta."),_("FindTimedChest"),_("Items.BFG")),
    Achievement(_("Engineer: Better With Friends"),_("As Engineer, recruit 12 minions at one time."),_("EngiArmy"),_("Skills.Engi.WalkerTurret")),
    Achievement(_("Engineer: Zero Sum"),_("As Engineer, finish charging the teleporter with zero monsters remaining on the stage."),_("EngiClearTeleporterWithZeroMonsters"),_("Skills.Engi.Harpoon")),
    Achievement(_("Newtist"),_("Discover and activate 8 unique Newt Altars."),_("FindUniqueNewtStatues"),_("Items.Talisman")),
    Achievement(_("The Long Road"),_("Complete 20 stages in a single run."),_("Complete20Stages"),_("Items.Clover")),
    Achievement(_("Huntress: One Shot, One Kill"),_("As Huntress, collect and carry 12 Crowbars at once."),_("HuntressCollectCrowbars"),_("Skills.Huntress.MiniBlink")),
    Achievement(_("Mercenary: Flash of Blades"),_("As Mercenary, use 20 abilities in 10 seconds."),_("MercXSkillsInYSeconds"),_("Skills.Merc.FocusedAssault")),
    Achievement(_("Bandit: Classic Man"),_("As Bandit, successfully use 'Lights Out' to reset your cooldowns 15 times in a row."),_("Bandit2ConsecutiveReset"),_("Skills.Bandit2.Rifle")),
    Achievement(_("Trial of Sacrifice"),_("Complete the Trial of Sacrifice."),_("ObtainArtifactSacrifice"),_("Artifacts.Sacrifice")),
    Achievement(_("Acrid: Easy Prey"),_("As Acrid, land the killing blow on 50 total enemies that have 1 hit point left."),_("CrocoKillWeakEnemiesMilestone"),_("Skills.Croco.PassivePoisonLethal")),
    Achievement(_("Mercenary: Demon of the Skies"),_("As Mercenary, don't touch the ground for 30 seconds"),_("MercDontTouchGround"),_("Skills.Merc.Uppercut")),
    Achievement(_("Trial of Swarms"),_("Complete the Trial of Swarms."),_("ObtainArtifactSwarms"),_("Artifacts.Swarms")),
    Achievement(_("Artificer: Orbital Bombardment"),_("As Artificer, kill 15 enemies before touching the ground."),_("MageAirborneMultiKill"),_("Skills.Mage.FlyUp")),
    Achievement(_("The Calm"),_("Beat the game on Monsoon difficulty."),_("CompleteMainEndingHard"),_("Items.LunarBadLuck")),
    Achievement(_("MUL-T: Pest Control"),_("As MUL-T defeat two Beetle Queens without leaving the teleporter zone."),_("ToolbotGuardTeleporter"),_("Skills.Toolbot.Grenade")),
    Achievement(_("Prismatically Aligned"),_("Complete a Prismatic Trial."),_("CompletePrismaticTrial"),_("Items.HealOnCrit")),
    Achievement(_("Glorious Battle"),_("Charge the Teleporter with less than 10% health."),_("ChargeTeleporterWhileNearDeath"),_("Items.KillEliteFrenzy")),
    Achievement(_("Engineer: 100% Calculated"),_("As Engineer, defeat the teleporter boss in less than 5 seconds after it spawns."),_("EngiKillBossQuick"),_("Skills.Engi.SpiderMine")),
    Achievement(_("Loader: Earthshatter"),_("As Loader, land a Charged Gauntlet hit at 300mph or higher."),_("LoaderBigSlam"),_("Skills.Loader.ZapFist")),
    Achievement(_("Huntress: Piercing Wind"),_("As Huntress, start and finish either Rallypoint Delta or Scorched Acres without falling bellow 100% health."),_("HuntressMaintainFullHealthOnFrozenWall"),_("Skills.Huntress.Snipe")),
    Achievement(_("Dragged Below"),_("Escape the Planetarium or complete wave 50 in Simulacrum."),_("CompleteVoidEnding"),_("Characters.VoidSurvivor")),
    Achievement(_("Aritificer: Massacre"),_("As Artificer, perform a multikill of 20 enemies."),_("MageMultiKill"),_("Skills.Mage.LightningBolt")),
    Achievement(_("Trial of Kin"),_("Complete the Trial of Kin."),_("ObtainArtifactSingleMonsterType"),_("Artifacts.SingleMonsterType")),
    Achievement(_("Commando: Rolling Thunder"),_("As Commando, land the killing blow on an Overloading Worm."),_("CommandoKillOverloadingWorm"),_("Skills.Commando.FireShotgunBlast")),
    Achievement(_("Huntress: Mastery"),_("As Huntress, beat the game or obliterate on Monsoon."),_("HuntressClearGameMonsoon"),_("Skins.Huntress.Alt1")),
    Achievement(_("Trial of Dissonance"),_("Complete the Trial of Dissonance."),_("ObtainArtifactMixEnemy"),_("Artifacts.MixEnemy")),
    Achievement(_("Trial of Glass"),_("Complete the Trial of Glass."),_("ObtainArtifactGlass"),_("Artifacts.Glass")),
    Achievement(_("Captain: Wanderlust"),_("As Captain, visit 10 different environments in a single run."),_("CaptainVisitSeveralStages"),_("Skills.Captain.CaptainSupplyDropEquipmentRestock")),
    Achievement(_("Captain: Worth Every Penny"),_("As Captain, repair and recruit a TC-280 Prototype."),_("CaptainBuyMegaDrone"),_("Skills.Captain.CaptainSupplyDropHacking")),
    Achievement(_("Commando: Incorruptible"),_("As Commando, clear 20 stages in a single run without picking up any Lunar items."),_("CommandoNonLunarEndurance"),_("Skills.Commando.ThrowGrenade")),
    Achievement(_("Acrid: Pandemic"),_("As Acrid, inflict Poison 1000 total times."),_("CrocoTotalInfectionsMilestone"),_("Skills.Croco.ChainableLeap")),
    Achievement(_("Trial of Vengeance"),_("Complete the Trial of Vengeance."),_("ObtainArtifactShadowClone"),_("Artifacts.ShadowClone")),
    Achievement(_("Commando: Mastery"),_("As Commando, beat the game or obliterate on Monsoon."),_("CommandoClearGameMonsoon"),_("Skins.Commando.Alt1")),
    Achievement(_("Engineer: Mastery"),_("As Engineer, beat the game or obliterate on Monsoon."),_("EngiClearGameMonsoon"),_("Skins.Engi.Alt1")),
    Achievement(_("Artificer: Chunked!"),_("As Artificer, fully defeat the teleporter boss in a one-second burst of damage."),_("MageFastBoss"),_("Skills.Mage.IceBomb")),
    Achievement(_("Mercenary: Mastery"),_("As Mercenary, beat the game or obliterate on Monsoon."),_("MercClearGameMonsoon"),_("Skins.Merc.Alt1")),
    Achievement(_("Trial of Chaos"),_("Complete the Trial of Chaos."),_("ObtainArtifactFriendlyFire"),_("Artifacts.FriendlyFire")),
    Achievement(_("Railgunner: Trickshot"),_("As Railgunner, get 3 kills with a single Supercharge shot while airborne."),_("RailgunnerAirborneMultiKill"),_("Skills.Railgunner.SpecialAlt1")),
    Achievement(_("Trial of Metamorphosis"),_("Complete the Trial of Metamorphosis."),_("ObtainArtifactRandomSurvivorOnRespawn"),_("Artifacts.RandomSurvivorOnRespawn")),
    Achievement(_("Trial of Enigma"),_("Complete the Trial of Engima."),_("ObtainArtifactEnigma"),_("Artifacts.Enigma")),
    Achievement(_("Trial of Death"),_("Complete the Trial of Death."),_("ObtainArtifactTeamDeath"),_("Artifacts.TeamDeath")),
    Achievement(_("Loader: Swing By"),_("As Loader, reach and proceed through the Celestial Portal in 25 minutes or less."),_("LoaderSpeedRun"),_("Skills.Loader.YankHook")),
    Achievement(_("Trial of Soul"),_("Complete the Trial of Soul."),_("ObtainArtifactWispOnDeath"),_("Artifacts.WispOnDeath")),
    Achievement(_("MUL-T: Mastery"),_("As MUL-T, beat the game or obliterate on Monsoon."),_("ToolbotClearGameMonsoon"),_("Skins.Toolbot.Alt1")),
    Achievement(_("Trial of Spite"),_("Complete the Trial of Spite."),_("ObtainArtifactBomb"),_("Artifacts.Bomb")),
    Achievement(_("The Demons And The Crabs"),_("Kill 20 Hermit Crabs by chasing them off the edge of the map"),_("SuicideHermitCrabs"),_("Items.AutoCastEquipment")),
    Achievement(_("Artificer: Mastery"),_("As Artificer, beat the game or obliterate on Monsoon."),_("MageClearGameMonsoon"),_("Skins.Mage.Alt1")),
    Achievement(_("Loader: Mastery"),_("As Loader, beat the game or obliterate on Monsoon."),_("LoaderClearGameMonsoon"),_("Skins.Loader.Alt1")),
    Achievement(_("Captain: Mastery"),_("As Captain, beat the game or obliterate on Monsoon."),_("CaptainClearGameMonsoon"),_("Skins.Captain.Alt1")),
    Achievement(_("Acrid: Bad Medicine"),_("As Acrid, land the final blow on a Scavenger."),_("CrocoKillScavenger"),_("Skills.Croco.CrocoBite")),
    Achievement(_("Trial of Evolution"),_("Complete the Trial of Evolution."),_("ObtainArtifactMonsterTeamGainsItems"),_("Artifacts.MonsterTeamGainsItems")),
    Achievement(_("Railgunner: Marksman"),_("As Railgunner, fire 30 consecutive sniper shots without missing a Weak Point."),_("RailgunnerConsecutiveWeakPoints"),_("Skills.Railgunner.SecondaryAlt1")),
    Achievement(_("Acrid: Mastery"),_("As Acrid, beat the game or obliterate on Monsoon."),_("CrocoClearGameMonsoon"),_("Skins.Croco.Alt1")),
    Achievement(_("Trial of Frailty"),_("Complete the Trial of Frailty."),_("ObtainArtifactWeakAssKnees"),_("Artifacts.WeakAssKnees")),
    Achievement(_("REX: Bushwhacked"),_("As REX, complete an entire teleporter event while under 50% health."),_("TreebotLowHealthTeleporter"),_("Skills.Treebot.Barrage")),
    Achievement(_("Bandit: Mastery"),_("As Bandit, beat the game or obliterate on Monsoon."),_("Bandit2ClearGameMonsoon"),_("Skins.Bandit2.Alt1")),
    Achievement(_("MUL-T: Gotcha!"),_("As MUL-T, land the killing blow on an Imp Overlord with the Preon Accumulator."),_("ToolbotKillImpBossWithBfg"),_("Skills.Toolbot.Buzzsaw")),
    Achievement(_("REX: Mastery"),_("As REX, beat the game or obliterate on Monsoon."),_("TreebotClearGameMonsoon"),_("Skins.Treebot.Alt1")),
    Achievement(_("Bandit: B&E"),_("As Bandit, kill the final boss with 'Lights Out'."),_("Bandit2RevolverFinale"),_("Skills.Bandit2.SkullRevolver")),
    Achievement(_("REX: Dunked"),_("As REX, kill a Clay Dunestrider on Abandoned Aqueduct by throwing it into a pit."),_("TreebotDunkClayBoss"),_("Skills.Treebot.PlantSonicBoom")),
    Achievement(_("Mercenary: Ethereal"),_("As Mercenary, complete a Prismatic Trial without falling below 100% health."),_("MercCompleteTrialWithFullHealth"),_("Skills.Merc.EvisProjectile")),
    Achievement(_("MUL-T: Seventh Day"),_("As MUL-T, clear the Void Fields on Stage 7 or later."),_("ToolbotBeatArenaLater"),_("Skills.Toolbot.SpecialAlt")),
    Achievement(_("REX: Full of Life"),_("As REX, heal for 1000 health at once."),_("TreebotBigHeal"),_("Skills.Treebot.SpecialAlt1")),
    Achievement(_("Bandit: Sadist"),_("As Bandit, kill a monster with 20 stacks of Hemorrhage."),_("Bandit2StackSuperBleed"),_("Skills.Bandit2.SerratedShivs")),
    Achievement(_("Loader: The Thunderdome"),_("As Loader, kill three other loaders in the Bulwark's Ambry."),_("LoaderKillLoaders"),_("Skills.Loader.Thunderslam")),
    Achievement(_("Railgunner: Annihiliator"),_("As Railgunner, deal 1,000,000 damage in one shot."),_("RailgunnerDealMassiveDamage"),_("Skills.Railgunner.UtilityAlt1")),
    Achievement(_("Railgunner: Mastery"),_("As Railgunner, beat the game or obliterate on Monsoon."),_("RailgunnerClearGameMonsoon"),_("Skins.RailGunner.Alt1")),
    Achievement(_("[V??oid Fiend] : Mastery"),_("As [V??oid Fiend], beat the game or obliterate on Monsoon."),_("VoidSurvivorClearGameMonsoon"),_("Skins.VoidSurvivor.Alt1")),
    Achievement(_("Captain: Smushed"),_("As Captain, kill the final boss using a Supply Beacon."),_("CaptainSupplyDropFinale"),_("Skills.Captain.UtilityAlt1"))
};

enum values{
    ELITE_SLAYER = 0,
    ADVANCEMENT,
    BASICS,
    WARRIOR,
    LONE_SURVIVOR,
    LEARNING_PROCESS,
    FUNDED,
    EXPERIMENTING,
    VERIFIED,
    KEYED_UP,
    IS_THIS_BUGGED,
    MACHO,
    DEJA_VU,
    BOOKWORM,
    BLOCKADE_BREAKER,
    ENGINEERING_PERFECTION,
    MULTIKILL,
    GUIDANCE_OFFLINE,
    SLAUGHTER,
    COSMIC_EXPLORER,
    I_LOVE_DYING,
    FLAWLESS,
    GOING_FAST_RECOMMENDED,
    MECHANIC,
    WARM_FOR_LIFE,
    ASCENDANT,
    WARMONGER,
    WASHED_AWAY,
    PAUSE,
    TRUE_RESPITE,
    CUT_DOWN,
    CLEANUP_DUTY,
    RAPIDFIRE,
    TO_BE_LEFT_ALONE,
    NEVER_BACK_DOWN,
    BLACKOUT,
    ONE_WITH_THE_WOODS,
    MAYBE_ONE_MORE,
    HER_CONCEPTS,
    NATUROPATH,
    DEATH_DO_US_PART,
    TRIAL_OD_HONOR,
    AUTOMATION_ACTIVATION,
    FINISHING_TOUCH,
    GODSPEED,
    TRIAL_OF_COMMAND,
    POWER_PLANT,
    MOON_WORSHIPPER,
    DEICIDE,
    REDACTED,
    BETTER_WITH_FRIENDS,
    ZERO_SUM,
    NEWTIST,
    LONG_ROAD,
    ONE_SHOT_ONE_KILL,
    FLAH_OF_BLADES,
    CLASSIC_MAN,
    TRIAL_OF_SACRIFICE,
    EASY_PREY,
    DEMON_OF_THE_SKIES,
    TRIAL_OF_SWARMS,
    ORBITAL_BOMBARDMENT,
    THE_CALM,
    PEST_CONTROL,
    PRISMATICALLY_ALIGNED,
    GLORIOUS_BATTLE,
    CALCULATED,
    EARTHSHATTER,
    PIERCING_WIND,
    DRAGGED_BELOW,
    MASSACRE,
    TRIAL_OF_KIN,
    ROLLING_THUNDER,
    HUNTRESS_MASTERY,
    TRIAL_OF_DISSONANCE,
    TRIAL_OF_GLASS,
    WANDERLUST,
    WORTH_EVERY_PENNY,
    INCORRUPTIBLE,
    PANDEMIC,
    TRIAL_OF_VENGEANCE,
    COMMANDO_MASTERY,
    ENGINEER_MASTERY,
    CHUNKED,
    MERCENARY_MASTERY,
    TRIAL_OF_CHAOS,
    TRICKSHOT,
    TRIAL_OF_METAMORPHOSIS,
    TRIAL_OF_ENIGMA,
    TRIAL_OF_DEATH,
    SWING_BY,
    TRIAL_OF_SOUL,
    MULT_MASTERY,
    TRIAL_OF_SPITE,
    THE_DEMONS_AND_THE_CRABS,
    ARTIFICER_MASTERY,
    LOADER_MASTERY,
    CAPTAIN_MASTERY,
    BAD_MEDICINE,
    TRIAL_OF_EVOLUTION,
    MARSKMAN,
    ACRID_MASTERY,
    TRIAL_OF_FRAILTY,
    BUSHWACKED,
    BANDIT_MASTERY,
    GOTCHA,
    REX_MASTERY,
    B_AND_E,
    DUNKED,
    ETHEREAL,
    SEVENTH_DAY,
    FULL_OF_LIVE,
    SADIST,
    THUNDERDOME,
    ANNIHILIATOR,
    RAILGUNNER_MASTERY,
    VOID_MASTERY,
    SMUSHED
};
#endif